# Generated by Django 4.1 on 2023-02-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HousePricePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sqft_living', models.IntegerField()),
                ('sqft_lot', models.IntegerField()),
                ('floors', models.DecimalField(decimal_places=1, max_digits=4)),
                ('waterfront', models.BooleanField()),
                ('view', models.IntegerField()),
                ('grade', models.IntegerField()),
                ('sqft_basement', models.IntegerField()),
                ('yr_renovated', models.IntegerField()),
                ('zipcode', models.CharField(max_length=5)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('predicted_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prediction_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
